import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <main className='flex flex-1 flex-col items-center justify-center p-24'>
      about
    </main>
  )
}
