import classNames from 'classnames'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { Key, Navigation } from '../components'
import './globals.css'

const menuShortcut = 'q'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={classNames(
          'bg-gray-900 text-gray-50 min-h-screen flex flex-col',
          inter.className,
        )}
      >
        <Navigation shortcut={menuShortcut} />

        {children}

        <div className='text-center py-8 text-sm opacity-50'>
          Hold <Key className='text-gray-400'>{menuShortcut}</Key> for
          navigation
        </div>
      </body>
    </html>
  )
}
